### ISSUE TITLE
请问支持k8s集群部署吗?

### ISSUE THREAD

**Issue by SandyJiang** [chensheng/tamboot-rocketmq-server#1]
请问支持k8s集群部署吗?比如部署一个3节点broker.需要改哪些东西.

**Comment by chensheng** [comment]
你要先编译上传docker镜像，然后修改deployment-namesrv.yml和deployment-broker.yml中的镜像地址

**Comment by chensheng** [comment]
> 请问支持k8s集群部署吗?比如部署一个3节点broker.需要改哪些东西.

你要先编译上传docker镜像，然后修改deployment-namesrv.yml和deployment-broker.yml中的镜像地址

**Comment by chensheng** [comment]
> 请问支持k8s集群部署吗?比如部署一个3节点broker.需要改哪些东西.



> > 请问支持k8s集群部署吗?比如部署一个3节点broker.需要改哪些东西.
> 
> 你要先编译上传docker镜像，然后修改deployment-namesrv.yml和deployment-broker.yml中的镜像地址

或者使用镜像registry.cn-shenzhen.aliyuncs.com/registry_tam/tamboot-rocketmq-server

**Comment by chensheng** [comment]
> > 请问支持k8s集群部署吗?比如部署一个3节点broker.需要改哪些东西.
> 
> 你要先编译上传docker镜像，然后修改deployment-namesrv.yml和deployment-broke

> 请问支持k8s集群部署吗?比如部署一个3节点broker.需要改哪些东西.

修改部署文件的镜像地址为或者使用镜像registry.cn-shenzhen.aliyuncs.com/registry_tam/tamboot-rocketmq-server

**Comment by SandyJiang** [comment]
万分感谢
